{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "temporal.serviceAccountName" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
    iam.gke.io/gcp-service-account: "{{ .Values.gcp.service_account }}@{{ .Values.gcp.project_id }}.iam.gserviceaccount.com"
{{- end -}}
